version: 2
jobs:
  rivers:
    docker:
      - image: quay.io/cybozu/golang:1.11-bionic
    working_directory: /work
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
      - run: golint -set_exit_status ./...
      - run: go build ./...
      - run: go test -race -v ./...
      - run: go vet ./...
  scripts:
    docker:
      - image: quay.io/cybozu/ubuntu-dev:18.04
    steps:
      - checkout
      - run: apt-get update
      - run: cd scripts; make setup SUDO=
      - run: cd scripts; make

workflows:
  version: 2
  main:
    jobs:
      - rivers
      - scripts
