version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.11-bionic
      - image: quay.io/coreos/etcd:v3.3
    working_directory: /work
    steps:
      - checkout
      - run: test -z "$(gofmt -s -l . | grep -v '^vendor' | tee /dev/stderr)"
      - run: golint -set_exit_status $(go list -mod=vendor ./... | grep -v /vendor/)
      - run: go build -mod=vendor ./...
      - run: go test -mod=vendor -race -v ./...
      - run: go vet -mod=vendor ./...
  scripts:
    docker:
      - image: quay.io/cybozu/ubuntu-dev:18.04
    steps:
      - checkout
      - run: apt-get update
      - run: cd scripts; make setup SUDO=
      - run: cd scripts; make

workflows:
  version: 2
  main:
    jobs:
      - build
      - scripts
