version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.10-bionic
    working_directory: /go/src/github.com/cybozu-go/cke-tools
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: test -z "$(goimports -d . | tee /dev/stderr)"
      - run: golint -set_exit_status ./...
      - run: go build ./...
      - run: go test -race -v ./...
