#!/usr/bin/python3

from argparse import ArgumentParser
import os
import sys
from tempfile import NamedTemporaryFile


def octint(v: str) ->int:
    return int(v, 8)


def main():
    p = ArgumentParser()
    p.add_argument('--dir-mode', type=octint, default='755',
                   help='permission bits for new directories')
    p.add_argument('--mode', type=octint, default='644',
                   help='permission bits for the file')
    p.add_argument('file', metavar='FILE', help='the filename to be created')

    ns = p.parse_args()
    if not os.path.isabs(ns.file):
        sys.exit('FILE must be an asbolute path')

    d = os.path.dirname(ns.file)
    os.makedirs(d, mode=ns.dir_mode, exist_ok=True)
    with NamedTemporaryFile(dir=d, delete=False) as f:
        f.write(sys.stdin.buffer.read())
        f.flush()
        os.fsync(f.fileno())
        os.chmod(f.name, ns.mode)
        os.rename(f.name, ns.file)


if __name__ == '__main__':
    main()
